name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
<<<<<<< HEAD
      - run: npm ci
      - run: npm install
        working-directory: server
      - run: npm run verify
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
=======
      - run: cd server && npm ci
      - run: cd server && npm run verify
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: server/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 68525dcb148468d1f3062927bff296da3aca06d4
